#!/usr/bin/env tsx
// Copyright (c) 2026 Sinthetix, LLC. All rights reserved.
// https://www.sinthetix.com

// ── generate-default-sql.ts ───────────────────────────────────────────────────
// Reads TypeScript seed definitions from app/services/orchestrator/src/seed/
// and writes a complete PostgreSQL installation/default.sql file.
// Run with: tsx scripts/generate-default-sql.ts

import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

import { BUILT_IN_PROGRAMS, CONFIG_FILE_TYPES } from '../app/services/orchestrator/src/seed/programs.js'
import { BUILT_IN_PROFILE_DEFS } from '../app/services/orchestrator/src/seed/profiles.js'
import { GRID_STRUCTURE } from '../app/services/orchestrator/src/seed/grid.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT = resolve(__dirname, '..')
const OUT = resolve(ROOT, 'installation', 'default.sql')

// ── Safe dollar-quoting ───────────────────────────────────────────────────────
// Uses $seed$...$seed$ as delimiter so plain $$ in content doesn't break quoting
function q(s: string): string {
  return `$seed$${s}$seed$`
}

function qBool(b: boolean): string {
  return b ? 'true' : 'false'
}

function jsonbLiteral(obj: unknown): string {
  return q(JSON.stringify(obj))
}

// ── Agency permissions per tier ───────────────────────────────────────────────
function agencyPermissions(tier: 1 | 2 | 3): string {
  if (tier === 1) {
    return jsonbLiteral({
      agentCreate: 'autonomous',
      agentDelete: 'autonomous',
      agentUpdate: 'autonomous',
      groupCreate: 'autonomous',
      groupUpdate: 'autonomous',
      groupDelete: 'autonomous',
      shellRun: 'autonomous',
    })
  }
  if (tier === 2) {
    return jsonbLiteral({
      agentCreate: 'deny',
      agentDelete: 'deny',
      agentUpdate: 'deny',
      groupCreate: 'deny',
      groupUpdate: 'deny',
      groupDelete: 'deny',
      shellRun: 'deny',
    })
  }
  // tier 3 (main)
  return jsonbLiteral({
    agentCreate: 'deny',
    agentDelete: 'deny',
    agentUpdate: 'request',
    groupCreate: 'request',
    groupUpdate: 'request',
    groupDelete: 'deny',
    shellRun: 'deny',
  })
}

// ── Profile slug assignment per program ──────────────────────────────────────
function profileSlugFor(id: string, tier: 1 | 2 | 3): string {
  if (tier === 1) return 'default'           // system and ctrl
  if (tier === 2) return 'default'           // all tier-2 workers
  if (id === 'main') return 'personal-assistant'
  return 'default'
}

// ── Lines collector ───────────────────────────────────────────────────────────
const lines: string[] = []

function emit(...args: string[]): void {
  for (const line of args) lines.push(line)
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. Header + extensions
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- Agency default.sql',
  '-- Generated by scripts/generate-default-sql.ts',
  `-- Generated at: ${new Date().toISOString()}`,
  '--',
  '-- Pipe into a fresh PostgreSQL container:',
  '--   psql -U agency -d agency < installation/default.sql',
  '--',
  '-- All inserts use ON CONFLICT DO NOTHING — file is idempotent.',
  '',
  'CREATE EXTENSION IF NOT EXISTS "pgcrypto";',
  '',
)

// ─────────────────────────────────────────────────────────────────────────────
// 2. Schema — CREATE TABLE statements
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- SCHEMA',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
  'CREATE TABLE IF NOT EXISTS agent_profiles (',
  '  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  name              TEXT NOT NULL,',
  '  slug              TEXT UNIQUE NOT NULL,',
  '  description       TEXT,',
  '  system_prompt     TEXT NOT NULL DEFAULT \'\',',
  '  model_tier        TEXT NOT NULL DEFAULT \'strong\',',
  '  model_override    TEXT,',
  '  allowed_tools     JSONB NOT NULL DEFAULT \'[]\',',
  '  behavior_settings JSONB NOT NULL DEFAULT \'{}\',',
  '  tags              JSONB NOT NULL DEFAULT \'[]\',',
  '  built_in          BOOLEAN NOT NULL DEFAULT false,',
  '  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS profile_config_files (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  profile_id UUID NOT NULL REFERENCES agent_profiles(id) ON DELETE CASCADE,',
  '  file_type  TEXT NOT NULL CHECK (file_type IN (\'identity\',\'soul\',\'user\',\'state\',\'directives\',\'decisions\',\'coordination\',\'governance\',\'memory\',\'history\',\'permissions\',\'profile\',\'prompt\',\'links\',\'heartbeat\',\'capabilities\',\'scratch\')),',
  '  content    TEXT NOT NULL DEFAULT \'\',',
  '  UNIQUE (profile_id, file_type)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS agent_identities (',
  '  id                          TEXT PRIMARY KEY,',
  '  name                        TEXT NOT NULL,',
  '  slug                        TEXT UNIQUE NOT NULL,',
  '  parent_agent_id             TEXT,',
  '  lifecycle_type              TEXT NOT NULL DEFAULT \'always_on\',',
  '  wake_mode                   TEXT NOT NULL DEFAULT \'auto\',',
  '  current_profile_id          TEXT,',
  '  shell_permission_level      TEXT NOT NULL DEFAULT \'none\',',
  '  agent_management_permission TEXT NOT NULL DEFAULT \'approval_required\',',
  '  agency_permissions          JSONB NOT NULL DEFAULT \'{}\',',
  '  autonomous_mode             BOOLEAN NOT NULL DEFAULT false,',
  '  workspace_path              TEXT NOT NULL,',
  '  additional_workspace_paths  JSONB NOT NULL DEFAULT \'[]\',',
  '  status                      TEXT NOT NULL DEFAULT \'active\',',
  '  created_by                  TEXT NOT NULL DEFAULT \'system\',',
  '  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  brain_node_id               UUID,',
  '  model_config                JSONB,',
  '  schedule                    TEXT,',
  '  schedule_enabled            BOOLEAN NOT NULL DEFAULT false,',
  '  last_run_at                 TIMESTAMPTZ,',
  '  next_run_at                 TIMESTAMPTZ,',
  '  run_count                   INT NOT NULL DEFAULT 0,',
  '  last_error                  TEXT',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS agent_config_files (',
  '  id            UUID    PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  agent_id      TEXT    NOT NULL REFERENCES agent_identities(id) ON DELETE CASCADE,',
  '  file_type     TEXT    NOT NULL CHECK (file_type IN (\'identity\',\'soul\',\'user\',\'state\',\'directives\',\'decisions\',\'coordination\',\'governance\',\'memory\',\'history\',\'permissions\',\'profile\',\'prompt\',\'links\',\'heartbeat\',\'capabilities\',\'scratch\')),',
  '  content       TEXT    NOT NULL DEFAULT \'\',',
  '  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_by    TEXT    NOT NULL DEFAULT \'system\',',
  '  brain_node_id UUID,',
  '  UNIQUE (agent_id, file_type)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS sessions (',
  '  id               TEXT PRIMARY KEY,',
  '  agent_id         TEXT NOT NULL,',
  '  client           TEXT NOT NULL DEFAULT \'cli\',',
  '  status           TEXT NOT NULL DEFAULT \'active\',',
  '  name             TEXT,',
  '  coordinator_mode BOOLEAN NOT NULL DEFAULT false,',
  '  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS messages (',
  '  id         TEXT PRIMARY KEY,',
  '  session_id TEXT NOT NULL REFERENCES sessions(id),',
  '  role       TEXT NOT NULL,',
  '  content    TEXT NOT NULL DEFAULT \'\',',
  '  tool_calls JSONB,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS approvals (',
  '  id           TEXT PRIMARY KEY,',
  '  agent_id     TEXT NOT NULL,',
  '  session_id   TEXT NOT NULL,',
  '  prompt       TEXT NOT NULL,',
  '  tool_name    TEXT,',
  '  tool_input   JSONB,',
  '  status       TEXT NOT NULL DEFAULT \'pending\',',
  '  risk_level   TEXT NOT NULL DEFAULT \'medium\',',
  '  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  resolved_at  TIMESTAMPTZ,',
  '  resolved_by  TEXT,',
  '  note         TEXT',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS model_usage (',
  '  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  agent_id      TEXT NOT NULL,',
  '  session_id    TEXT,',
  '  model         TEXT NOT NULL,',
  '  input_tokens  INT NOT NULL DEFAULT 0,',
  '  output_tokens INT NOT NULL DEFAULT 0,',
  '  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS skills (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  name        TEXT UNIQUE NOT NULL,',
  '  slug        TEXT UNIQUE NOT NULL,',
  '  version     TEXT NOT NULL DEFAULT \'0.0.1\',',
  '  type        TEXT NOT NULL DEFAULT \'general\',',
  '  description TEXT,',
  '  content     TEXT NOT NULL DEFAULT \'\',',
  '  source_path TEXT,',
  '  built_in    BOOLEAN NOT NULL DEFAULT false,',
  '  enabled     BOOLEAN NOT NULL DEFAULT true,',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS agent_skills (',
  '  agent_id TEXT NOT NULL,',
  '  skill_id UUID NOT NULL REFERENCES skills(id) ON DELETE CASCADE,',
  '  enabled  BOOLEAN NOT NULL DEFAULT true,',
  '  PRIMARY KEY (agent_id, skill_id)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS memory_entries (',
  '  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  agent_id      TEXT NOT NULL,',
  '  type          TEXT NOT NULL DEFAULT \'episodic\'',
  '                CHECK (type IN (\'episodic\',\'semantic\',\'working\',\'procedural\',\'reflective\')),',
  '  content       TEXT NOT NULL,',
  '  embedding     JSONB,',
  '  tags          JSONB NOT NULL DEFAULT \'[]\',',
  '  importance    FLOAT NOT NULL DEFAULT 0.5,',
  '  memory_status TEXT NOT NULL DEFAULT \'active\'',
  '                CHECK (memory_status IN (\'active\',\'proposal\',\'canon\',\'deprecated\',\'archived\')),',
  '  scope_type    TEXT NOT NULL DEFAULT \'agent\'',
  '                CHECK (scope_type IN (\'system\',\'agent\',\'zone\',\'global\')),',
  '  scope_id      TEXT,',
  '  visibility    TEXT NOT NULL DEFAULT \'private\'',
  '                CHECK (visibility IN (\'private\',\'zone\',\'global\')),',
  '  trust_level   SMALLINT NOT NULL DEFAULT 1,',
  '  promoted_by   TEXT,',
  '  promoted_at   TIMESTAMPTZ,',
  '  brain_node_id UUID,',
  '  expires_at    TIMESTAMPTZ,',
  '  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS vault_documents (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  path        TEXT UNIQUE NOT NULL,',
  '  title       TEXT NOT NULL DEFAULT \'\',',
  '  content     TEXT NOT NULL DEFAULT \'\',',
  '  frontmatter JSONB NOT NULL DEFAULT \'{}\',',
  '  status      TEXT NOT NULL DEFAULT \'active\',',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS vault_entities (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  document_id UUID NOT NULL REFERENCES vault_documents(id) ON DELETE CASCADE,',
  '  name        TEXT NOT NULL,',
  '  type        TEXT NOT NULL,',
  '  properties  JSONB NOT NULL DEFAULT \'{}\',',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  UNIQUE(document_id)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS vault_links (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  from_doc   UUID NOT NULL REFERENCES vault_documents(id) ON DELETE CASCADE,',
  '  to_doc     UUID NOT NULL REFERENCES vault_documents(id) ON DELETE CASCADE,',
  '  link_text  TEXT,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS vault_sync_events (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  event_type TEXT NOT NULL,',
  '  file_path  TEXT NOT NULL,',
  '  status     TEXT NOT NULL DEFAULT \'ok\',',
  '  error      TEXT,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS audit_log (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  action      TEXT NOT NULL,',
  '  actor       TEXT NOT NULL,',
  '  target_type TEXT,',
  '  target_id   TEXT,',
  '  details     JSONB,',
  '  sensitive   BOOLEAN NOT NULL DEFAULT false,',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS hooks (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  event      TEXT NOT NULL,',
  '  agent_id   TEXT,',
  '  command    TEXT NOT NULL,',
  '  enabled    BOOLEAN NOT NULL DEFAULT true,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS tool_overrides (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  agent_id   TEXT NOT NULL,',
  '  tool_name  TEXT NOT NULL,',
  '  override   JSONB NOT NULL DEFAULT \'{}\',',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  UNIQUE (agent_id, tool_name)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS mcp_servers (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  name       TEXT UNIQUE NOT NULL,',
  '  command    TEXT NOT NULL,',
  '  args       JSONB NOT NULL DEFAULT \'[]\',',
  '  env        JSONB NOT NULL DEFAULT \'{}\',',
  '  enabled    BOOLEAN NOT NULL DEFAULT true,',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS agent_mcp (',
  '  agent_id  TEXT NOT NULL,',
  '  server_id UUID NOT NULL REFERENCES mcp_servers(id) ON DELETE CASCADE,',
  '  PRIMARY KEY (agent_id, server_id)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS workspace_groups (',
  '  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  name           TEXT NOT NULL,',
  '  slug           TEXT UNIQUE NOT NULL,',
  '  description    TEXT,',
  '  workspace_path TEXT NOT NULL,',
  '  is_system      BOOLEAN NOT NULL DEFAULT false,',
  '  brain_node_id  UUID,',
  '  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS workspace_group_members (',
  '  group_id UUID NOT NULL REFERENCES workspace_groups(id) ON DELETE CASCADE,',
  '  agent_id TEXT NOT NULL,',
  '  PRIMARY KEY (group_id, agent_id)',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS scheduled_triggers (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  name        TEXT NOT NULL,',
  '  schedule    TEXT NOT NULL,',
  '  agent_id    TEXT NOT NULL,',
  '  prompt      TEXT NOT NULL,',
  '  enabled     BOOLEAN NOT NULL DEFAULT true,',
  '  last_run_at TIMESTAMPTZ,',
  '  next_run_at TIMESTAMPTZ,',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS brain_nodes (',
  '  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  type        TEXT NOT NULL,',
  '  label       TEXT NOT NULL,',
  '  content     TEXT NOT NULL DEFAULT \'\',',
  '  tags        JSONB NOT NULL DEFAULT \'[]\',',
  '  embedding   JSONB,',
  '  confidence  FLOAT NOT NULL DEFAULT 1.0,',
  '  source      TEXT NOT NULL DEFAULT \'system\',',
  '  grid_path   TEXT,',
  '  grid_tier   SMALLINT NOT NULL DEFAULT 0,',
  '  grid_locked BOOLEAN NOT NULL DEFAULT false,',
  '  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()',
  ');',
  '',
  'CREATE TABLE IF NOT EXISTS brain_edges (',
  '  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  '  from_id    UUID NOT NULL REFERENCES brain_nodes(id) ON DELETE CASCADE,',
  '  to_id      UUID NOT NULL REFERENCES brain_nodes(id) ON DELETE CASCADE,',
  '  type       TEXT NOT NULL,',
  '  weight     FLOAT NOT NULL DEFAULT 1.0,',
  '  source     TEXT NOT NULL DEFAULT \'system\',',
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),',
  '  UNIQUE (from_id, to_id, type)',
  ');',
  '',
)

// ─────────────────────────────────────────────────────────────────────────────
// 3. Indexes
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- INDEXES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
  'CREATE UNIQUE INDEX IF NOT EXISTS brain_nodes_grid_path_unique_idx ON brain_nodes(grid_path) WHERE grid_path IS NOT NULL;',
  'CREATE INDEX IF NOT EXISTS brain_nodes_grid_tier_idx ON brain_nodes(grid_tier) WHERE grid_tier > 0;',
  'CREATE INDEX IF NOT EXISTS idx_sessions_agent_id ON sessions(agent_id);',
  'CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id);',
  'CREATE INDEX IF NOT EXISTS idx_approvals_status ON approvals(status);',
  'CREATE INDEX IF NOT EXISTS idx_approvals_agent_id ON approvals(agent_id);',
  'CREATE INDEX IF NOT EXISTS acf_agent_id_idx ON agent_config_files(agent_id);',
  'CREATE INDEX IF NOT EXISTS pcf_profile_id_idx ON profile_config_files(profile_id);',
  'CREATE INDEX IF NOT EXISTS ai_brain_node_id_idx ON agent_identities(brain_node_id) WHERE brain_node_id IS NOT NULL;',
  'CREATE INDEX IF NOT EXISTS me_memory_status_idx ON memory_entries(memory_status);',
  'CREATE INDEX IF NOT EXISTS me_scope_idx ON memory_entries(scope_type, scope_id);',
  '',
)

// ─────────────────────────────────────────────────────────────────────────────
// 4. Grid structural brain_nodes (first pass — all nodes)
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- GRID STRUCTURAL NODES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const node of GRID_STRUCTURE) {
  emit(
    `INSERT INTO brain_nodes (type, label, content, grid_path, grid_tier, grid_locked, source)`,
    `VALUES (`,
    `  ${q(node.type)},`,
    `  ${q(node.label)},`,
    `  ${q(node.content)},`,
    `  ${q(node.grid_path)},`,
    `  ${node.grid_tier},`,
    `  true,`,
    `  $seed$system$seed$`,
    `)`,
    `ON CONFLICT (grid_path) WHERE grid_path IS NOT NULL DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 5. Grid brain_edges (parent → child, second pass so all nodes exist)
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- GRID STRUCTURAL EDGES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const node of GRID_STRUCTURE) {
  if (!node.parent_path || !node.edge_type) continue
  emit(
    `INSERT INTO brain_edges (from_id, to_id, type, source)`,
    `SELECT`,
    `  p.id,`,
    `  c.id,`,
    `  ${q(node.edge_type)},`,
    `  $seed$system$seed$`,
    `FROM brain_nodes p, brain_nodes c`,
    `WHERE p.grid_path = ${q(node.parent_path)}`,
    `  AND c.grid_path = ${q(node.grid_path)}`,
    `ON CONFLICT (from_id, to_id, type) DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 6. Built-in agent_profiles
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- BUILT-IN AGENT PROFILES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const profile of BUILT_IN_PROFILE_DEFS) {
  emit(
    `INSERT INTO agent_profiles (name, slug, description, model_tier, built_in)`,
    `VALUES (`,
    `  ${q(profile.name)},`,
    `  ${q(profile.slug)},`,
    `  ${q(profile.description)},`,
    `  ${q(profile.modelTier)},`,
    `  true`,
    `)`,
    `ON CONFLICT (slug) DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 7. profile_config_files (17 blank files per profile)
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- PROFILE CONFIG FILES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const profile of BUILT_IN_PROFILE_DEFS) {
  for (const fileType of CONFIG_FILE_TYPES) {
    emit(
      `INSERT INTO profile_config_files (profile_id, file_type, content)`,
      `SELECT id, ${q(fileType)}, $seed$$seed$`,
      `FROM agent_profiles WHERE slug = ${q(profile.slug)}`,
      `ON CONFLICT (profile_id, file_type) DO NOTHING;`,
      '',
    )
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 8. agent_identities for all 13 built-in programs
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- AGENT IDENTITIES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  const schedule = prog.schedule ? q(prog.schedule) : 'NULL'
  const scheduleEnabled = qBool(prog.scheduleEnabled ?? false)
  emit(
    `INSERT INTO agent_identities (`,
    `  id, name, slug, lifecycle_type, shell_permission_level,`,
    `  agent_management_permission, agency_permissions, workspace_path,`,
    `  schedule, schedule_enabled`,
    `) VALUES (`,
    `  ${q(prog.id)},`,
    `  ${q(prog.name)},`,
    `  ${q(prog.slug)},`,
    `  ${q(prog.lifecycleType)},`,
    `  ${q(prog.shellPermissionLevel)},`,
    `  ${q(prog.agentManagementPermission)},`,
    `  ${agencyPermissions(prog.tier)},`,
    `  ${q(`agents/${prog.slug}`)},`,
    `  ${schedule},`,
    `  ${scheduleEnabled}`,
    `)`,
    `ON CONFLICT (id) DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 9. Link each program's current_profile_id to the appropriate profile
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- LINK AGENT IDENTITIES → PROFILES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  const profileSlug = profileSlugFor(prog.id, prog.tier)
  emit(
    `UPDATE agent_identities`,
    `SET current_profile_id = (SELECT id FROM agent_profiles WHERE slug = ${q(profileSlug)})`,
    `WHERE id = ${q(prog.id)} AND current_profile_id IS NULL;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 10 & 11. Brain nodes for each program + edges to parent
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- PROGRAM BRAIN NODES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  emit(
    `INSERT INTO brain_nodes (type, label, content, grid_path, grid_tier, grid_locked, source)`,
    `VALUES (`,
    `  $seed$program$seed$,`,
    `  ${q(prog.slug.toUpperCase())},`,
    `  ${q(prog.description)},`,
    `  ${q(prog.gridPath)},`,
    `  ${prog.tier},`,
    `  true,`,
    `  $seed$system$seed$`,
    `)`,
    `ON CONFLICT (grid_path) WHERE grid_path IS NOT NULL DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 11. Brain edges linking each program's brain node to its parent
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- PROGRAM BRAIN EDGES (program node → parent grid node)',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  emit(
    `INSERT INTO brain_edges (from_id, to_id, type, source)`,
    `SELECT`,
    `  p.id,`,
    `  c.id,`,
    `  $seed$contains$seed$,`,
    `  $seed$system$seed$`,
    `FROM brain_nodes p, brain_nodes c`,
    `WHERE p.grid_path = ${q(prog.gridParentPath)}`,
    `  AND c.grid_path = ${q(prog.gridPath)}`,
    `ON CONFLICT (from_id, to_id, type) DO NOTHING;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 12. Update agent_identities.brain_node_id
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- LINK AGENT IDENTITIES → BRAIN NODES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  emit(
    `UPDATE agent_identities`,
    `SET brain_node_id = (SELECT id FROM brain_nodes WHERE grid_path = ${q(prog.gridPath)})`,
    `WHERE id = ${q(prog.id)} AND brain_node_id IS NULL;`,
    '',
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// 13. agent_config_files — 17 blank files per program
// ─────────────────────────────────────────────────────────────────────────────
emit(
  '-- ─────────────────────────────────────────────────────────────────────────',
  '-- AGENT CONFIG FILES',
  '-- ─────────────────────────────────────────────────────────────────────────',
  '',
)

for (const prog of BUILT_IN_PROGRAMS) {
  for (const fileType of CONFIG_FILE_TYPES) {
    emit(
      `INSERT INTO agent_config_files (agent_id, file_type, content)`,
      `VALUES (${q(prog.id)}, ${q(fileType)}, $seed$$seed$)`,
      `ON CONFLICT (agent_id, file_type) DO NOTHING;`,
      '',
    )
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Write output
// ─────────────────────────────────────────────────────────────────────────────
const sql = lines.join('\n')
writeFileSync(OUT, sql, 'utf8')

const programCount = BUILT_IN_PROGRAMS.length
const profileCount = BUILT_IN_PROFILE_DEFS.length
const fileTypeCount = CONFIG_FILE_TYPES.length
const gridNodeCount = GRID_STRUCTURE.length

console.log(`✓ Written to ${OUT}`)
console.log(`  ${programCount} programs × ${fileTypeCount} config files`)
console.log(`  ${profileCount} profiles × ${fileTypeCount} profile files`)
console.log(`  ${gridNodeCount} Grid structural nodes`)
